// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using odevvv.Models;

#nullable disable

namespace odevvv.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221225180319_deneme")]
    partial class deneme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("odevvv.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("Kullanici")
                        .HasColumnType("VarChar(20)");

                    b.Property<string>("Sifre")
                        .HasColumnType("VarChar(10)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("odevvv.Models.Hayvanlar", b =>
                {
                    b.Property<int>("HayvanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HayvanID"));

                    b.Property<int>("HayvanAgirlik")
                        .HasColumnType("int");

                    b.Property<string>("HayvanCins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HayvanCinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HayvanIrk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HayvanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HayvanYas")
                        .HasColumnType("int");

                    b.Property<string>("Hayvanİmage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HayvanID");

                    b.ToTable("Hayvanlars");
                });

            modelBuilder.Entity("odevvv.Models.UserRole", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
